### ISSUE TITLE
회원가입 완료 시 해당 유저를 로그인 처리

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#100]
회원가입 완료시 해당 유저에 대한 토큰을 발급하여 바로 로그인하는 효과를 주고싶습니다. 사용자가 회원가입 후 로그인을 다시 해야하는 번거로움도 없어지고(UX), 서버도 로그인 요청을 따로 받지 않아도 되니 좋은 생각 같은데 어떠신가요.

**Comment by galaxy4276** [comment]
그렇게 구현하시면 될 거 같습니다.
전적으로 프런트에서 처리해주는 부분이에요.

**Comment by bear-bear-bear** [comment]
회원가입 success 처리와 동시에 해당 유저에 대한 토큰 값을 내려주면 서버 비용이 줄어들 것 같은데 어떤가요?

**Comment by galaxy4276** [comment]
그렇게 처리할게요!

**Comment by galaxy4276** [comment]
로그인 했을 때와 동일하게 accessToken 은 쿠키로, refreshToken 은 객체 내용에 포함되어서 전달됩니다.
