### ISSUE TITLE
로그인한 유저가 받아오는 정보

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#107]
클로징된 [#101](https://github.com/bear-bear-bear/mogakco/pull/101) 관련해서 말인데요, 재확인 하고 싶어서요, 죄송합니다.
 
``` js
state.me === {
  id: 1, // 아이디 
  username: '최은기', // 나한테만 보이는 이름
  skills: [], // 백에서 id, string 내려줌. 백으로 보낼땐 id, 프론트에서 사용할 땐 string. 이후 어드민에서 추가 가능
  job: '',
}
```
분야는 skills, 직업은 job으로 설정하는 것 맞지요?
기존 프론트 코드랑 달라서 헷갈려서요

**Comment by galaxy4276** [comment]
맞습니다.

**Comment by galaxy4276** [comment]
백엔드 내용이랑 다르다고 혼란스러울 필요 없으셔요
두 파트 간 데이터를 맞춘다는 규칙은 없슴다
