### ISSUE TITLE
user가 갖는 skills의 길이 제한

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#114]
분야가 랭킹 집계를 위한건데, 한 유저가 모든 분야 찍어놓고 서비스 이용하면 저희 의도하고 다른 행동인 듯 하네요. skills 길이제한이 필요하다 생각합니다. 3~5정도가 적당하다 생각하는데 어떠세요?

**Comment by galaxy4276** [comment]
어떤 말씀이신지 정확히 이해가 어렵습니다.
분야의 name length 길이 or 최대 설정할 수 있는 관심 분야 갯수??

**Comment by bear-bear-bear** [comment]
말이 모호했네요, 후자입니다. 전자는 어차피 사용자가 아닌 어드민이 설정하는거니 상관 없겠지요

**Comment by bear-bear-bear** [comment]
자라고요

**Comment by galaxy4276** [comment]
괜찮은거 같습니다!! 정말 타당합니다

**Comment by galaxy4276** [comment]
귀하를 김디버그라 칭하겠습니다

**Comment by bear-bear-bear** [comment]
뭔가 김치버거같고 좋네요 감사합니다

**Comment by galaxy4276** [comment]
기획인지 변경요청인지에 대한 구분이 필요하겠네요 라벨 하나 만들어주세영

**Comment by bear-bear-bear** [comment]
왜 시키세요?

**Comment by bear-bear-bear** [comment]
바로 가서 만들어오겠습니다

**Comment by galaxy4276** [comment]
![image](https://user-images.githubusercontent.com/50310464/120115540-16c73380-c1bf-11eb-8f24-e476a8f6cba1.png)
민트 김치는 어떠신가요

**Comment by galaxy4276** [comment]
@bear-bear-bear @wscrg 이 기능 자체가 프런트 백 모두 반영되기 전까지 Close 금지.
한쪽에서 먼저 완성된다면 다른 측에 어서 완성해달라 협박하기

**Comment by galaxy4276** [comment]
라벨 내가 먼저 선수 침

**Comment by bear-bear-bear** [comment]
ㅂㅁㄷㅂㄷㅂㄷㅂㄷㅂㄷㅂㄷㅂㄷ

**Comment by galaxy4276** [comment]
#122 적용 완료
