### ISSUE TITLE
개발 분야, 직업 필드 should no exist

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#115]
![image](https://user-images.githubusercontent.com/57123802/120115779-41fe5280-c1c0-11eb-89b3-6d225753c3b4.png)

개발 분야 (skills) API가 완성되었음에도 같은 메세지가 나타나 이슈 올립니다.

**Comment by galaxy4276** [comment]
회원가입쪽 아직 안되있어요..

**Comment by galaxy4276** [comment]
아까 슬랙에서 고지드렸습니다

**Comment by galaxy4276** [comment]
#122 적용 완료
