### ISSUE TITLE
백엔드 시딩 환경 완료 및 사용법 작성

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#123]
## 환경 구성
![image](https://user-images.githubusercontent.com/50310464/120516732-a44a9380-c40a-11eb-853b-c739d85eec5d.png)
- .env.example 두 값을 그대로 .env 에 복사합니다.

##### 시더를 실행하기 전에 항상 npm run schema:drop && npm run schema:sync 를 진행해주세요! ( 안해도 무리는 없으나, 해주는 것이 좋습니다. )
- npm run seed:run 명령 수행 시 시더가 수행되면서, 데이터베이스에 자동으로 데이터가 입력됩니다.
##### ex)
![image](https://user-images.githubusercontent.com/50310464/120516912-d78d2280-c40a-11eb-94a7-f43f974225be.png)

#### 현재 이용 가능 06-04

**Comment by bear-bear-bear** [comment]
시더를 실행한다는건, 서버를 실행한다는 말이지요?

**Comment by bear-bear-bear** [comment]
아 아니구나

**Comment by bear-bear-bear** [comment]
npm run seeder:run  >> npm run seed:run

현재 nest/package.json에 npm run seeder:run 으로 설정되어 있어요

**Comment by galaxy4276** [comment]
수정 완료

**Comment by galaxy4276** [comment]
숙지 기간 충분 판단하에 close
