### ISSUE TITLE
이메일 인증 링크 클릭 시에 리다이렉션 링크 변경 요청

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#132]
기존에 이메일 인증 결과를 쿼리에 담아 /signup 페이지로 리다이렉션 시켜줬는데, 리다이렉션 주소를 /callback 페이지로 변경 요청드려도 될까요?

**Comment by galaxy4276** [comment]
그럼 /signup 주소도 /callback 으로 변경되는건가요? REST 규칙에 어긋나는거 같습니다.

**Comment by bear-bear-bear** [comment]
아뇨, callback은 말그대로 callback 기능만 담당합니다. 위에 말씀드린 회원가입여부 검증 혹은 OAuth 리다이렉션 처리 등을 담당할 것 같아요. REST라.. 페이지 이름을 redirection 으로 할까요?

**Comment by galaxy4276** [comment]
백엔드에서 이메일인증 url 클릭 후 redirection 주소를 /callback 으로 옮긴다면, 로컬 회원가입처리는 어떻게 되는건가요?

**Comment by bear-bear-bear** [comment]
쿼리를 받아 success 여부를 검증해서 상태 변경 후, signup 페이지로 이동하게 됩니다.

**Comment by galaxy4276** [comment]
/callback 이라는 라우터는 OAuth 와 관련된 라우터 아닌가요?
왜 본문에서 왜 /callback 으로 변경을 요청하는지도 설명해주시면 좋을 것 같습니다.

**Comment by bear-bear-bear** [comment]
기존에 signup 페이지로 먼저 리다이렉션 한 후 상태를 변경하여 다음단계를 렌더링 하는 방식은, 일단 회원가입 페이지 첫 단계를 사용자한테 보여준 후 다음 단계로 이동하는 방식이라 깜박임처럼 보이는 UX 문제가 있었습니다. 해서 SSR을 적용할 것으로 기존에 계획했었는데, OAuth 에서도 해당 서비스의 이메일을 받아서 해당 이메일이 DB 에 있다면 로그인 처리를, 없다면 회원가입 추가정보 입력 페이지로 이동해야 하는 처리를 담당하는 /callback이 있어  비슷한 성격의 두 로직을 한 페이지에 두려고 합니다.

**Comment by galaxy4276** [comment]
> 쿼리를 받아 success 여부를 검증해서 상태 변경 후, signup 페이지로 이동하게 됩니다.

중간 단인 callback 에서 한번 더 검증처리가 되어야 하는 이유를 알 수 있을까요?

**Comment by galaxy4276** [comment]
> 기존에 signup 페이지로 먼저 리다이렉션 한 후 상태를 변경하여 다음단계를 렌더링 하는 방식은, 일단 회원가입 페이지 첫 단계를 사용자한테 보여준 후 다음 단계로 이동하는 방식이라 깜박임처럼 보이는 UX 문제가 있었습니다. 해서 SSR을 적용할 것으로 기존에 계획했었는데, OAuth 에서도 해당 서비스의 이메일을 받아서 해당 이메일이 DB 에 있다면 로그인 처리를, 없다면 회원가입 추가정보 입력 페이지로 이동해야 하는 처리를 담당하는 /callback이 있어 비슷한 성격의 두 로직을 한 페이지에 두려고 합니다.

OAuth 로 회원가입 했다면, 이미 로그인 처리를 수행하고,
결과적으로 처리해야 할 로직이 한 개( 단순함) 가 아니게 되었기 때문에 별도의 처리 페이지를 둔다는 거군요.
제가 이해한게 맞나요? 
곧 올라갈 PR에 함께 적용해서 올리겠습니다.

**Comment by bear-bear-bear** [comment]
부족하여 궁금한 점이 있는데, /callback 은 OAuth에 필수적인가요? SSR로 처리할수는 없는 것인지?

**Comment by bear-bear-bear** [comment]
> OAuth 로 회원가입 했다면, 이미 로그인 처리를 수행하고,
> 결과적으로 처리해야 할 로직이 한 개( 단순함) 가 아니게 되었기 때문에 별도의 처리 페이지를 둔다는 거군요.
> 제가 이해한게 맞나요?
> 곧 올라갈 PR에 함께 적용해서 올리겠습니다.

네 일단은 이말이 맞습니다

**Comment by galaxy4276** [comment]
> 부족하여 궁금한 점이 있는데, /callback 은 OAuth에 필수적인가요? SSR로 처리할수는 없는 것인지?

무슨 말씀인지 잘 모르겠습니다.
OAuth 인증방식은 보통 callback url 을 설정해두고, 인증처리에 대한 반환 여부를 처리합니다.

**Comment by galaxy4276** [comment]
서버에서 한번에 Oauth 처리과정을 수행하고 결과를 반환할 수 없냐는 뜻일까요?

**Comment by bear-bear-bear** [comment]
아. /callback은 필수군요. 이해했습니다.

**Comment by bear-bear-bear** [comment]
> 서버에서 한번에 Oauth 처리과정을 수행하고 결과를 반환할 수 없냐는 뜻일까요?

어라 ,, 이거 되지 않나요? 이메일 검증 true 로 해주는 GET API마냥 OAuth 처리 API를 따로 두면?

**Comment by bear-bear-bear** [comment]
라고 하면 전 매우 편하겠지만, 무조건 SSR 적용하는게 좋은 건 아니기 때문에 이건 /callback으로 하는게 맞는 것 같습니다

**Comment by bear-bear-bear** [comment]
참았습니다.

**Comment by bear-bear-bear** [comment]
> 어라 ,, 이거 되지 않나요? 이메일 검증 true 로 해주는 GET API마냥 OAuth 처리 API를 따로 두면?

그 API를 OAuth callback URI 로 등록해두는거죠 ㅋㅋ

**Comment by galaxy4276** [comment]
뭔가 많이 생략된 느낌이에요

**Comment by galaxy4276** [comment]
OAuth 를 프런트에서 처리한다는 말씀이신지..

**Comment by galaxy4276** [comment]
그리고 지금 보류상태 아닌가요?

**Comment by galaxy4276** [comment]
> > 서버에서 한번에 Oauth 처리과정을 수행하고 결과를 반환할 수 없냐는 뜻일까요?
> 
> 어라 ,, 이거 되지 않나요? 이메일 검증 true 로 해주는 GET API마냥 OAuth 처리 API를 따로 두면?


?????

**Comment by bear-bear-bear** [comment]
OAuth 방식이 제가 이해한게 맞다면,
1. 사용자가 구글 로그인 버튼 클릭하고 들어가서 로그인
2. 구글에서 설정한 callback URL로 액세스 토큰 발급
3. 리다이렉션 된 callback URL에서 해당 액세스 토큰으로 구글에 검증 요청
4. 맞다면 시크릿 토큰과 리프레쉬 토큰 발급
5. 해당 토큰들로 설정된 정보 범위에 대한 API 요청, 발급된 토큰의 refresh 가능

**Comment by galaxy4276** [comment]
대화에서 안된다고 말한게 아닙니다

**Comment by bear-bear-bear** [comment]
어라. 여기서 말한 callback URL이 프론트 페이지가 아니라 백엔드 라우터 인가요..?

**Comment by bear-bear-bear** [comment]
아웅 헷갈려

**Comment by bear-bear-bear** [comment]
이론만 읽어서 뭐가 뭔지 원

**Comment by galaxy4276** [comment]
> 서버에서 한번에 Oauth 처리과정을 수행하고 결과를 반환할 수 없냐는 뜻일까요?
> 어라 ,, 이거 되지 않나요? 이메일 검증 true 로 해주는 GET API마냥 OAuth 처리 API를 따로 두면?
대화에서 안된다고 말한게 아닙니다
