### ISSUE TITLE
기획 변경 ( 사용자 회원 가입 )

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#133]
직업 항목은 무조건 선택 가능하게 끔 해야할 것 같습니다.

잘 생각해보면 희망 분야만 optional 이고 직업항목은 required 처리가 됩니다.
만약 사용자가 반사회성으로 인해 선택의사가 없다면, 기타 항목으로 선택하게끔 처리하면 될듯 합니다. ( seed 데이터 참조 )
* * *
![image](https://user-images.githubusercontent.com/50310464/120882391-851e5280-c612-11eb-82a1-f74f58b4a9d2.png)

**Comment by bear-bear-bear** [comment]
왜 희망 분야만 optional 이고 직업항목은 required 처리가 되는지 알려주실 수 있나용
