### ISSUE TITLE
회원가입 이메일 인증 시 깜박임 문제

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#134]
![#](https://user-images.githubusercontent.com/57123802/120883785-2066f600-c61a-11eb-8850-54f9c24a815b.gif)

### Why?
다음 단계로 넘어가는 state 변경이 회원가입 첫 페이지에서 리다이렉션 URL의 params의 useEffect 검증으로 이뤄지기 때문. 회원가입 첫 페이지가 렌더링 된 후에야 검증 시작

### How solve?
1. SSR 처리
2. /redirection 페이지에서 params 검증, state 변경 수행

둘 중 한 방법으로 해결하기

**Comment by galaxy4276** [comment]
이 부분 까다로우면 그대로 두시면 제가 해결할게요

**Comment by bear-bear-bear** [comment]
?? 안까다로워

**Comment by bear-bear-bear** [comment]
근데 어떻게 처리하게,?

**Comment by galaxy4276** [comment]
안알려줌

**Comment by bear-bear-bear** [comment]
?? 프론트 아무것도 안해도 백단서 처리한다고?

**Comment by galaxy4276** [comment]
제가 프런트 건들건데용

**Comment by bear-bear-bear** [comment]
ㅂㄷㅂㄷ

**Comment by bear-bear-bear** [comment]
?
params 관련 처리를 useEffect에서 처리하는게 아니라 회원가입 첫 페이지 컴포넌트 자체에서 처리하면 (params 조건 만족시 액션 dispatch 후 return null, 불만족시 기존 회원가입 첫 페이지 return) 되는거 아닌지? 타입스크립트 학습 후 적용해볼 예정

**Comment by galaxy4276** [comment]
아직 해결 안됬나요? @bear-bear-bear
