### ISSUE TITLE
이미 가입된 유저임에도 이메일 검증 API가 success=true를 반환하는 문제

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#137]
![image](https://user-images.githubusercontent.com/57123802/120935726-1559b600-c73f-11eb-9980-a7fee2fa7833.png)
![image](https://user-images.githubusercontent.com/57123802/120935754-34f0de80-c73f-11eb-9e1b-a9a455ba6b44.png)

**Comment by galaxy4276** [comment]
이 부분 놓쳤네요.
오전 중, "이미 가입되었으면 가입 불가능" 테스트 로직과 함께 PR 올리겠습니다.

**Comment by galaxy4276** [comment]
SQL 고수시네요

**Comment by bear-bear-bear** [comment]
이미 가입되어 있다면 쳐내는건 sendEmail에서도 추가하는게 맞는 것 같은데 어떻개 생각하세요
