### ISSUE TITLE
프론트단에서 skills 혹은 job을 null로 세팅해서 회원가입 요청시 에러 코드를 반환하는 문제

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#138]
skills와 job은 선택적인 정보 (최근 PR에서 백단에서 null 받을 수 있게 처리해주신 것 같았는데 아니였나요?)

![image](https://user-images.githubusercontent.com/57123802/120936105-1b509680-c741-11eb-98bb-66c4c9fb1f3a.png)

**Comment by galaxy4276** [comment]
지금 null 로 보내면 될거에요.
[] -> null 처리 파이프 적용하겠습니다

**Comment by bear-bear-bear** [comment]
엥 null 처리 했는데 프론트에서

**Comment by bear-bear-bear** [comment]
![image](https://user-images.githubusercontent.com/57123802/120937073-5e613880-c746-11eb-8c6f-4f939dafdae4.png)
앗

**Comment by bear-bear-bear** [comment]
아냐 프론트에서 null로 보낼게

**Comment by bear-bear-bear** [comment]
아 이거 해결 안되어 있는 것 같은데?

**Comment by bear-bear-bear** [comment]
135번 PR까지 반영된 작업 상태인데

**Comment by bear-bear-bear** [comment]
![image](https://user-images.githubusercontent.com/57123802/120937314-d714c480-c747-11eb-8d04-351abd72f61f.png)
둘 다 null로 보내면 빈 값 올 수 없다는거 나오구 skills는 null로 보냈을때 5개 이상 보낼 수 없다는 메세지까지 같이 반환 중
