### ISSUE TITLE
이메일 인증 후 리다이렉션이 서버 주소로 가고있는 문제

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#142]
![image](https://user-images.githubusercontent.com/57123802/121017075-d4fa4680-c7d7-11eb-9670-fa5fd6092b8c.png)
![image](https://user-images.githubusercontent.com/57123802/121017120-de83ae80-c7d7-11eb-93c3-29f45b6bc855.png)

**Comment by galaxy4276** [comment]
.env 에 SERVER_PORT 없나요?
없으시면 추가해주시고, 포트 값 설정해주세요

**Comment by galaxy4276** [comment]
일단 템플릿 지우고 localhost:8001 로 바꿔서 진행하는거도 좋아요

**Comment by bear-bear-bear** [comment]
ㅋㅋ 아녀 그 문제가 아니라

**Comment by bear-bear-bear** [comment]
저기 프론트 포트 들어가야 할 자리인데 서버 포트 넣어서 404  욤

**Comment by bear-bear-bear** [comment]
리다이렉션 이자나여 8001 대신 3000 넣으면 정상 작동

**Comment by galaxy4276** [comment]
zzzzzzzzzzzzz 졸렸나봄 저거하고 바로 기절했어용..

**Comment by galaxy4276** [comment]
이거 수정 됨.
