### ISSUE TITLE
로그인 관련 안내사항

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#144]
## 로그인 관련 안내 사항
1. 로그인 전략
   - JWT - access_token, refresh_token
2. 로그인 응답 값
3. 보안
4. Api 테스트 하는 법 ( 전체적인 흐름을 확인하기 )

### 1. 로그인 전략
* JWT 토큰을 사용하여, 클라이언트 자체적으로 인증을 관리하며 서버와 통신하여 만료기간을 체크하고, 권한을 주는 방식입니다.
* 첫 로그인 시, accessToken, refreshToken 이 발급되며, accessToken 의 만료시간은 10분, refreshToken 의 만료시간은 1주일 입니다.
* accessToken 이 만료되어, 인증이 불가능할 경우, refreshToken 을 검증하여 새롭게 accessToken 을 발급하는 방식입니다.

##### ⚠ accessToken 은 쿠키, refreshToken 은 Response 개체에 동봉됩니다. ⚠ 
* * *
```
{
    "statusCode": 200,
    "message": "로그인에 성공하였습니다!",
    "user": {
        "id": 1,
        "username": "mogauser",
        "email": "mogakco35@gmail.com",
        "skills": [
            {
                "id": 1,
                "name": "안드로이드"
            },
            {
                "id": 4,
                "name": "프론트엔드"
            },
            {
                "id": 8,
                "name": "정보보안"
            },
            {
                "id": 9,
                "name": "IOS"
            },
            {
                "id": 10,
                "name": "백엔드"
            }
        ],
        "job": {
            "id": 1,
            "name": "보안 솔루션 개발자"
        }
    },
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJtb2dhdXNlciIsImlhdCI6MTYyMzI1NDM4MiwiZXhwIjoxNjIzMzE0ODYyfQ.KjpTi9nEP-us_Rl7IK1cTbI2UGTFmeEaZEGS_95qsQU",
   "accessExpiredDate": "2021-06-25T11:57:29.615Z"
}
```
* * *
### 3. 보안
* 클라이언트에서 쿠키를 조작하지 못하는 설정을 부여했으며, acccessToken 이 탈취되더라도, 유효기간이 10분이므로 보안성이 우수합니다.
* 백엔드에서 secret 키를 알고 있지 않는 한, 인증 토큰은 해독될 수 없습니다.
* * *
### 4. Api 테스트 하는 법 ( 전체적인 흐름 확인 )
* api 는 Postman 도구에만 소개하나, 사용에 대한 설명이 필요하기 때문에 첨부합니다.
* * *
#### 로그인
* POST /api/auth/login
* login 은 email, password 정보를 필요로 합니다.
* 기존 시딩 데이터에 테스트 계정을 이용해주세요. ( mogakco35@gmail.com / mogapass )
![image](https://user-images.githubusercontent.com/50310464/121381871-111cdb00-c981-11eb-8e76-0618ce281e48.png)
* Postman 다음과 같은 요청 시, **로그인 성공 메시지, 유저에 대한 정보, refreshToken** 이 JSON 객체 값으로 전달됩니다.
**⚠Postman에서 Api 를 테스트 하기 위해서, refreshToken 을 복사해두셔야 합니다.⚠**
* **accessToken 이 쿠키 값**으로 따로 설정됩니다.
![image](https://user-images.githubusercontent.com/50310464/121382161-4de8d200-c981-11eb-9c42-60c0461cfea1.png)
* * *
#### 로그인 상태 테스트
* GET /api/auth/test
* * Postman Authorization Bearer Token 에 로그인 시 복사했던 토큰 값을 넣어주세요. ( refereshToken 검증 후 accessToken 재발급 Api 참조 )
* 로그인 중이라면, accessToken 쿠키 정보와, 유저에 대한 정보를 Response 합니다.
![image](https://user-images.githubusercontent.com/50310464/121382057-37427b00-c981-11eb-8b1f-f2504ce1d896.png)
![image](https://user-images.githubusercontent.com/50310464/121388526-83dc8500-c986-11eb-94e1-7adfa7a2c5a1.png)
* * *
#### refreshToken 검증 후 accessToken 재발급
* GET /api/auth/refresh-token
* Postman Authorization Bearer Token 에 로그인 시 복사했던 토큰 값을 넣어주세요.
* **갱신 성공에 대한 메시지와 유저에 대한 정보 객체**가 반환됩니다.
![image](https://user-images.githubusercontent.com/50310464/121388726-aff80600-c986-11eb-8cd4-2ec0850da3d6.png)
![image](https://user-images.githubusercontent.com/50310464/121388876-ce5e0180-c986-11eb-8d13-0e7d8106efb5.png)
![image](https://user-images.githubusercontent.com/50310464/121388902-d3bb4c00-c986-11eb-9f5a-3faf06447c1f.png)
* * *
* #### 로그아웃
* POST /api/auth/logout
* Postman Authorization Bearer Token 에 로그인 시 복사했던 토큰 값을 넣어주세요.
* 데이터베이스에서 refreshToken 을 영구삭제하고 accessToken 쿠키 또한 리셋하여 반환합니다.
![image](https://user-images.githubusercontent.com/50310464/121389101-06fddb00-c987-11eb-987e-4a0f89fe447c.png)
* * *
### 프런트엔드 로그인 전략

1. 서버에서 첫 로그인 성공 응답에 access 토큰의 만료 시간인 expiredAt(typeof Date)를 포함시키기
2. 클라이언트에서 해당 expiredAt를 리덕스 전역 state에 저장
3. 클라이언트에서 각 요청을 보낼 때마다 axios interceptors에서 리덕스 전역 state에 저장한 expiredAt 와 Data.now()를 비교하여 만료 시간을 넘었을 시 기존 요청을 잠시 멈춰두고 로컬 스토리지에서 refresh 토큰을 가져와 access토큰 갱신 요청을 먼저 보내기
4. access 토큰이 갱신되어 응답이 오면 잠시 멈춰둔 기존 요청의 access token을 갱신하여 서버로 전송
구현 완료 시 close

**Comment by bear-bear-bear** [comment]
확인

**Comment by bear-bear-bear** [comment]
로그인 구현 완료시 close

**Comment by bear-bear-bear** [comment]
무지인을 위해 상세한 설명 감사해요

**Comment by bear-bear-bear** [comment]
#221
