### ISSUE TITLE
커밋 메세지 형식 획일화

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#145]
![image](https://user-images.githubusercontent.com/57123802/121303219-cd50b400-c935-11eb-9f13-6eba7cfec5c5.png)

통일 시켜야 할 필요성이 있어요~ 하나 정해서 가죠

**Comment by galaxy4276** [comment]
ㅗㅡㅑ

**Comment by bear-bear-bear** [comment]
![image](https://user-images.githubusercontent.com/57123802/121383642-8fc64800-c982-11eb-814c-dbff079c867c.png)

**Comment by galaxy4276** [comment]
오늘 이후로 반영 예정. 어기면 칸초 기프티콘 콜?

**Comment by bear-bear-bear** [comment]
칸초 기프티콘은 쌉인정이지;
