### ISSUE TITLE
프런트엔드 타입스크립트 전환 안내사항

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#151]
## Content
* 타입스크립트로 변경하는데 next 공식문서에서 기존 확장자를 .tsx 로 권고합니다. ( 개인 희망사항으로 인한 변경 아님! )
> You're now ready to start converting files from .js to .tsx and leveraging the benefits of TypeScript!. ( [typescript-next](https://nextjs.org/docs/basic-features/typescript) )
* 기존 데이터들 중, props 를 내려주는데, 해당 컴포넌트에서 arg 로 받지않는 부분 임의로 수정했습니다.
* Props 로 받는 데이터에 대한 타입정보가 없어서 any 로 처리해두었습니다. 당장 수정해주셔야 하는 부분이 아니며, 타입스크립트가 적응되면 천천히 바꾸셔도 되고 공부 & 연습용으로 조금씩 수정해주시면서 변경하시면 될 것 같습니다.
* * *
* 타입스크립트를 공부하면서 정말 애용~했던 문서가 있습니다.
업로드할테니, 작업하실 때, 옆 화면에 열어두시고 작업하시면 좋을 것 같습니다.

> [Heropy 타입스크립트 가이드](https://heropy.blog/2020/01/27/typescript/)

**Comment by bear-bear-bear** [comment]
ㅜㅜ
