### ISSUE TITLE
프런트엔드 잘못된 컴포넌트 위치 수정 요청

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#155]
![image](https://user-images.githubusercontent.com/50310464/121798369-d35dd200-cc60-11eb-971c-fadb73e93ffb.png)
## Summary
* React 프레임워크 관점에서 common 디렉터리는 재사용가능한, 확장가능한 컴포넌트를 배치해놓고 여러 페이지들에서 확장하는 방식, 재사용하는 방식으로 이용하는 공용 컴포넌트를 배치해두는 공간으로 이해했습니다.
* 그러나 Input 디렉터리는 잘못된 방향성을 가지고 있는 것 같습니다. ( 특정 페이지에 대한 목적을 명시해둔 점, ex ) Email, Password .. ) 외에도 컴포넌트들이 공통 코드를 소지하고 있는 점.

## My Opinion
*  children 등으로 받아내는 방식으로 한 컴포넌트만을 남겨놓고 외부에서 확장하는 방식으로 변경하는 것이 좋을 듯 합니다.

**Comment by galaxy4276** [comment]
로그인, 회원가입 두 페이지에서 재사용할 의도로 설계되었다면, common 내부가 아닌 components/auth 로 디렉터리 구조를 수정하고 배치하는게 어떨까요?

**Comment by bear-bear-bear** [comment]
적어주신 의견 맞는 것 같아요. 저도 해당 코드 적으면서 반복되는 코드에 고민이 생겼던 참이였습니다.

**Comment by bear-bear-bear** [comment]
> 로그인, 회원가입 두 페이지에서 재사용할 의도로 설계되었다면, common 내부가 아닌 components/auth 로 디렉터리 구조를 수정하고 배치하는게 어떨까요?
기존에 정한 디렉터리 구조 컨벤션에는 일단 어긋납니다. 로그인, 회원가입 페이지는 각각 `pages/login.js`, `pages/signup.js` 으로 생성될 예정이고, components/ 안에선 각 페이지명을 따라 `components/login/`, `components/signup/` 에서 관련 컴포넌트를 다루게 되거든요.
Next.js의 다이나믹 라우팅을 통한 정적 페이지 생성 기능으로 말씀하신 것과 비슷한 방식으로 변경 가능할지 검토해볼게요.

**Comment by bear-bear-bear** [comment]
Next.js, TypeScript, testing 학습 완료 후 변경 예정

**Comment by galaxy4276** [comment]
컴포넌트에 대한 구조가 프런트엔드 파트에서 항상 이슈가되고, 고민이 되는 주제라고 하네요!
답안 감사합니다
