### ISSUE TITLE
프런트엔드 E2E 테스트 도입 안내사항

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#159]
## Feature
* Cypress 라는 프런트엔드 통합 테스트 라이브러리를 도입하였습니다.
* Mocha 테스트 프레임워크 위에 지어진 테스팅 도구라고 공식에서 소개하였으며, 유저 즉 클라이언트에서 다양한 입력, 행위를 테스트할 수 있습니다.
* 사용법은 공식문서를 참고하세요!
* * *
## 현재, 프로젝트에서 흐름을 간단히 테스트하는 방법
* next 위치에서 npm run cyrpess:open
* cypress 애플리케이션에서 landing.ts 클릭

**Comment by bear-bear-bear** [comment]
확인 했습니다.

**Comment by bear-bear-bear** [comment]
실제 적용할 레벨이 되면 close 하겠습니다
