### ISSUE TITLE
프런트엔드 스토리북 도입 안내사항

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#161]
## Summary
* 스토리북은 작성한 컴포넌트만 따로 View 에서 테스트할 수 있게 해주는 라이브러리입니다.
* * *
[스토리북 공식 홈](https://storybook.js.org/) <- 한국어 지원합니다.
[스토리북 NHN Cloud 정리 글](https://meetup.toast.com/posts/178)

**Comment by bear-bear-bear** [comment]
실제 적용할 수 있게되면 close할게요
