### ISSUE TITLE
FIX: 서버실행 시 소켓 커넥션

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#216]
![image](https://user-images.githubusercontent.com/50310464/124349896-7a180b80-dc2c-11eb-818c-674654129de6.png)
헤에...? 아무도 서비스를 안쓰는데 유령이 접속해버렷..

![image](https://user-images.githubusercontent.com/50310464/124349912-9025cc00-dc2c-11eb-8a85-b29bcb35f9da.png)

* * *
* 원인을 찾아서 해결하기

**Comment by bear-bear-bear** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
