### ISSUE TITLE
FIX: 로컬스토리지 수동 삭제 시 useEffect 무한 발생

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#232]
# Summary
* 근원지는 pages/_app.tsx useEffect 내부입니다. storage 이벤트에 대한 중복처리를 해결해야합니다.

**Comment by galaxy4276** [comment]
galaxy4276 local PC 에서 발생 확인이 안되고 있습니다.

**Comment by bear-bear-bear** [comment]
회원가입 start 페이지 제외 ㄱㄱ

**Comment by galaxy4276** [comment]
> 회원가입 start 페이지 제외 ㄱㄱ

발생하지 않습니다.

**Comment by bear-bear-bear** [comment]
회원가입이라 했는데 로그인 페이지 하는건 무슨 심보!

**Comment by galaxy4276** [comment]
무슨말씀인지 잘 모르겠어요 회원가입에서 시도해보라는것인가요?
회원가입, start 페이지 제외면 두 페이지 제외하고 나머지에서 발생아닌가요

**Comment by bear-bear-bear** [comment]
``` js
  /**
   * @desc 다른 페이지에서 로그아웃 할 시 감지하여 AccessToken 을 지워버립니다.
   */
  useEffect(() => {
    const refreshStore = async () => {
      refreshAccessTokenApi().catch(() => {
        memoryStore.delete(Memory.ACCESS_TOKEN);
      });
    };

    window.addEventListener('storage', refreshStore);
    return () => window.removeEventListener('storage', refreshStore);
  });
```
이 로직 문제가 많은 듯 합니다.

![image](https://user-images.githubusercontent.com/57123802/124953044-bfcf3c80-e04f-11eb-8416-59ecbc050007.png)
로컬 스토리지에서 뭐 건드릴때 계속 10초 1만 API콜 무한 루프 발생..
