### ISSUE TITLE
FEAT: change pages/ structure and create custom header for route

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#238]
## 해결하고자 하는 것
1. 인증이 필요한 서비스에 `비로그인 상태로` 접근 시 랜딩 페이지로 보내기
2. `로그인 상태로` 인증이 필요하지 않은 서비스에 접근 시 대쉬보드 페이지로 보내기
---
``` js
// next.config.js
// https://nextjs.org/docs/api-reference/next.config.js/redirects#header-cookie-and-query-matching
module.exports = {
...
  async redirects() {
    return [
      {
        source: '/',
        has: [
          {
            type: 'header',
            key: 'x-authorized',
            value: 'true',
          },
        ],
        permanent: false,
        destination: '/service/',
      },
      {
        source: '/auth/:path*',
        has: [
          {
            type: 'header',
            key: 'x-authorized',
            value: 'true',
          },
        ],
        permanent: false,
        destination: '/service/',
      },
      {
        source: '/service/:path*',
        has: [
          {
            type: 'header',
            key: 'x-authorized',
            value: 'false',
          },
        ],
        permanent: false,
        destination: '/',
      },
    ];
  },
...
```
결론부터 말하면, 서버단에서 req 헤더 필드에 커스텀 헤더 (예제에선 x-authorized) 를 로그인 , 로그아웃 때 'true' 혹은 'false'로 설정해주고, next.config.js에 위와 같이 설정하여 특정 페이지 접근 시 로그인/로그아웃 상태에 따른 클라이언트단 리다이렉션이 가능해집니다. 해서 요구되는 변경사항은 다음과 같습니다.

---
## 1
![image](https://user-images.githubusercontent.com/57123802/125123405-938bec80-e131-11eb-88f0-6e73ebbab703.png)
클라이언트단 페이지 구조를 이렇게 바꾸어야 합니다( 원활한 라우팅을 위해 ). 이러면 서버단 리다이렉션 주소 등 또한 변경되어야 합니다.

## 2
위와 같이 페이지 구조가 바뀐다면 클라이언트단에서 router.push() 등에 사용 된 문자열 경로들을 모두 수정해야 합니다.

## 3
서버단에서 로그인, 로그아웃에 따라 사전에 합의된 커스텀 헤더에 'true' 혹은 'false' 문자열을 매칭해주어야 합니다.

---
### [여기보면](https://nextjs.org/docs/api-reference/next.config.js/redirects#header-cookie-and-query-matching) 헤더 말고 쿠키나 쿼리도 리다이렉션 조건문에 넣을 수 있다는데, 로그인 여부는 쿠키에 리프레쉬 토큰이 있는가 없는가로 구분하면 되지 않나요?
next.config.js에서 쿠키의 `특정 키값이 존재하는가?` 혹은 `존재한다면 ~값과 일치 하는가?` 라는 조건은 설정할 수 있지만,
 `특정 키값이 존재 안하는가?`에 대한 조건은 설정할 수 없습니다. 
 즉, `리프레쉬 토큰이 존재하는가?` 조건으로 `로그인 상태로 인증이 필요하지 않은 서비스에 접근` 은 방지할 수 있지만, 
`리프레쉬 토큰이 존재하지 않는가?` 라는 조건은 없기 때문에,
 `인증이 필요한 서비스에 비로그인 상태로 접근`은 방지할 수 없습니다. 
해서 후자 또한 방지하기 위해 `로그인/로그아웃 상태에 따라 각기 다른 값으로 변하는 무언가`를 얻어야 하고,
 이 때문에 커스텀 헤더 추가 정의 등을 해줄 필요가 있습니다.
> 확인

### 사용자가헤더를 임의값으로 조작해서 들어올 수 있지 않나요?
맞습니다. 위험할 거라고 해봐야 비로그인 상태로 chat 페이지 등에 접근하는건데, 어차피 오류를 뿜어댈거고
어느 페이지든 잘못된 접근을 성공한다해도 저희 서비스 성격상 큰 보안 문제는 없다고 생각합니다.
어디까지나 실험적으로 url에 다른 값 넣어보는 호기심 많은 사용자들을 위한 방지책이니까요
> 확인

### 졸린가요?
네

![enter](https://i.stack.imgur.com/vf4aN.jpg)

**Comment by galaxy4276** [comment]
현재 인증이 필요한 모든 페이지에 대해서 각 페이지마다 SSR 코드를 작성하지 않고
next.confg.js 에서 처리를 하고싶은데, has 속성에서 조건에 대해 문제가 있기때문에 우리는 커스텀헤더를 사용해야 한다로 이해하면 될까요?

**Comment by galaxy4276** [comment]
긍정적으로 생각합니다.

**Comment by bear-bear-bear** [comment]
네 위에서 언급했듯이 백에서 해줘야 하는건
1. x-authrized 커스텀 헤더를 로그인 로그아웃 시 'true' | 'false' 로 추가해주는 것
2. Pages/ 디렉터리 경로 변경에 맞춰 백단에서도 변경 (sign-up/required 리다이렉션 등)

**Comment by galaxy4276** [comment]
저녁에 30분안에 작업해서 PR 만들어두겠습니다.

**Comment by bear-bear-bear** [comment]
https://github.com/bear-bear-bear/mogakco/pull/241
