### ISSUE TITLE
REQUEST: useUser.tsx 전반적 수정 요청

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#253]
* 백엔드에서 내려주는 값과 다릅니다. ( user 정보 props 를 사용하신 부분이 없어서 개발 중 문제가 없었 던 것으로 판단 됨 )
* 타입이 제대로 작동하지 않습니다. IUserSuccess... | IUserFail... 부분에 의해 정상적으로 동작하지 않는 듯 합니다.
* 주석 정보가 너무 많습니다. 코드 시작 이후 주석은 없어도 될듯하고, JSDoc 으로 주신 부분도 너무 과합니다.
* page/chat/[id].tsx 에서 userId 를 넣어주는 부분에서 정상적으로 추론되어 사용 될 수 있도록 바꿔주세요.

결론적으로, [id].tsx 에서 사용하는데 문제 없게 끔 수정해주시면 좋을 것 같습니다.
파일을 확인해보니 백엔드에서 바꿔주어야할 필요성은 없어보입니다.

**Comment by bear-bear-bear** [comment]
타입 수정 완료했습니다 죄송합니다.

user 응답도 통상 서버 응답 구조 스키마를 포함하는 걸로 잘못 알아서 생긴 타입 오류였습니다.

**Comment by bear-bear-bear** [comment]
서버에서 유저 정보에 대한 응답이 아래와 같이 오고 있는데,

![image](https://user-images.githubusercontent.com/57123802/128638514-2d04339f-f517-426d-9611-5473ebfd5632.png)

기존 요청드린 기획은 응답으로 온 데이터 내부에 user 정보가 spread 되어 있어서 res.data.username 등으로 접근할 수 있게 해달라는거였는데, 지금은 user 정보가 한번 wrapping 되어 있어서 res.data.user.username으로 접근해야 합니다. 수정해주세요~

**Comment by bear-bear-bear** [comment]
![image](https://user-images.githubusercontent.com/57123802/128638676-38fdd0f2-16da-44bc-8247-756ccfc3cf22.png)

저 id가 undefined인것도 위 이유 때문입니다.
기대하신건 user.id 이지만 현재 응답 구조상으론 user.user.id 인 것..
