### ISSUE TITLE
ANNOUNCEMENT: 백엔드 공사 견적 알림 내역

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#256]
# Summary
_* Nest Directory Structure 변경 [Best way Nest 2021](https://medium.com/the-crowdlinker-chronicle/best-way-to-structure-your-directory-code-nestjs-a06c7a641401)_ -완료
_* TypeORM Seed Library 제거 예정 ( 라이브러리 내 path-alias 관련 이슈 ) [대안 교체 방안]_(https://github.com/edwardanthony/nestjs-seeder) - 해결
* Postman -> Swagger API 문서화 및 자동 테스트 도구 교체 및 새롭게 도입 예정 
* ORM 관련된 코드 모두 한번 씩 점검 예정
* 반복되는 부분들 수정 예정
* mail 관련 라이브러리 교체 가능성 있음
* Error Handling 부분 코드 모두 한번에 갈아 치울 예정
_* 전체적인 모듈을 좀더 세분화하여서 설계 할 예정 ( 재사용성, SRP: single responsibility principle )_ - 완료
* * *
* 이 외에도 추가적인 사항에 대해서 지속적으로 작성하겠습니다.

**Comment by bear-bear-bear** [comment]
확인했습니다
