### ISSUE TITLE
[BUG] api/auth/user 에서 발생하는 에러

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#289]
버그 설명
---
api/auth/user 에서 발생하는 에러
<br>
<br>

재현하기 위해
---
버그가 발생하기 까지의 동작을 재현:
1. useUser 훅스가 적용된 아무 페이지 (사실상 모든 페이지) 에 접속
2. 백엔드 로그 확인
<br>
<br>

예상했던 결과
---
정상 동작
<br>
<br>

서버 로그 스크린샷
---
![image](https://user-images.githubusercontent.com/57123802/132493060-424416c2-9cc0-4407-829d-811b5681de7a.png)
<br>
<br>

추가 내용
---

**Comment by galaxy4276** [comment]
버그 재현 상황이 정확하지 않네요.
처음 로그인 시도 후 일반적으로 사용하는데 발생하지 않습니다.
저도 확인은 했으나 어쩔 때 걸려서 발생하는 지 모르겠습니다.
Token 이 만료되었을 때를 추측하거나, interceptor 로직 중에 문제가 있음을 유추해봅니다.

**Comment by bear-bear-bear** [comment]
특정 if 문에서 응답 완료 후 return  하지 않은 부분이 아닐까 싶은데 짐작가는곳 있으신가요

**Comment by bear-bear-bear** [comment]
코드 까보니 그렇게 단순하지 않았다..

**Comment by galaxy4276** [comment]
ㅋㅋㅋㅋ 일단 제가 리팩터링하면서 발생하는 듯 하니 프런트 문제가 아닌거같아요
백엔드 테스트 작성중입니다.

**Comment by galaxy4276** [comment]
현재 useUser 가 사용하기 까다로운데 #290 이랑 PR 확인해보시고 이어서 수정 부탁드릴게요.
