### ISSUE TITLE
[BUG] 잘못된 api 처리 ( Logout )

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#290]
버그 설명
---
버그에 대한 명확하고 간결한 설명.
<br>
 로그아웃 후 서버에서 던지는 Response의 데이터타입

```
export interface IGeneralServerResponse {
  message: string;
  statusCode: number;
  error?: string | string[];
}
```
해당 데이터 타입을 useUser 의 mutate 에 반영하고 있음
![image](https://user-images.githubusercontent.com/50310464/132500762-96a463d1-6d4e-4551-8549-f4e06e28c041.png)

useUser 데이터 타입

```
export interface IUserInfo {
  id: number;
  username: string;
  email: string;
  skills: IOptionalProps[] | null;
  job: IOptionalProps | null;
}

```
```
export interface IUserGetSuccessResponse extends IUserInfo {
  isLoggedIn: boolean; // true
}
```

<br>

재현하기 위해
---
버그가 발생하기 까지의 동작을 재현:
1. '...'로 이동
2. '....'를 클릭합니다.
3. '....'까지 아래로 스크롤합니다.
4. 오류 보기
<br>
<br>

예상했던 결과
---
위 동작을 통해 예상했던 결과에 대한 명확하고 간결한 설명.
<br>
<br>

서버 로그 스크린샷
---
해당 버그가 발생했을 때 서버 로그 스크린샷을 추가해주세요
<br>
<br>

추가 내용
---
문제에 대한 추가 내용이 있다면 여기에 적어주세요.

**Comment by galaxy4276** [comment]
#291 에서 UserFail.. 인터페이스를 useUser, SWRConfig 에 포함하게 끔 해주어서 해당 구문이 가능했었는데,
제가 삭제하면서 불가능하게 되었습니다.
generalResponse 까지 mutate 에 반영해야하는 이유가 있나요?
( isLoggedIn: false 정보면 로그아웃되었음에 충분하다고 판단됩니다. )

**Comment by bear-bear-bear** [comment]
작성 때 서버에서 generalResponse 를 포함한 데이터까지 준다고 가정하고 타입을 작성하여 저런 코드가 짜여졌는데, generalResponse 를 포함하지 않는다는걸 알고 타입은 수정했는데 코드는 수정하지 않았네요. 변경 감사합니다.

**Comment by bear-bear-bear** [comment]
관련부분 수정해서 #291에 추가하겠습니다
