### ISSUE TITLE
[FEATURE] 로그 아웃 후에는 ACCESS_TOKEN 을 갱신시키는 요청을 보내지 않음

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#295]
어떤 문제에 대한 기능 요청인지 설명
---
    로그 아웃 후에는 /api/auth/refresh-token api 로 액세스 토큰을 새로 갱신받아오는 요청을 보내지 않게 끔 수정해주셨으면 합니다.

( 리프레시 토큰 쿠키는 서버에서 로그아웃시 즉각적으로 지워주고 있습니다. )

원하는 솔루션 설명
---
<br>
프런트에서 기존 인터셉터와 useUser 로직을 검사하고 로그아웃 상태에서는 새 토큰 갱신 요청이 오지 않게 수정해주세요.

<br>

추가 내용
---
문제에 대한 추가 내용이 있다면 여기에 적어주세요.
![image](https://user-images.githubusercontent.com/50310464/132590949-a3e7c284-0b5b-4b19-b5a2-bb74b4983a35.png)
![image](https://user-images.githubusercontent.com/50310464/132591286-663144df-2c9b-41d0-8dcd-4aca1da7f504.png)

**Comment by bear-bear-bear** [comment]
정확히는 로컬스토리지에 리프레쉬 토큰이 없을 경우 해당 요청을 보내지 않았으면 한다는거군요

**Comment by galaxy4276** [comment]
아닙니다.

**Comment by galaxy4276** [comment]
제가 아는 한 로컬스토리지에 리프레시 토큰을 보관하지 않습니다.
그리고 #296 에 작업해뒀어요.

**Comment by bear-bear-bear** [comment]
미안합니다 말을 잘못했어요

**Comment by bear-bear-bear** [comment]
로컬스토리지 > 쿠키
