### ISSUE TITLE
[FEATURE] color 와 media를 emotion theme으로 관리

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#314]
어떤 문제에 대한 기능 요청인지 설명
---
현재 각각 emotion css global variable로 관리 하고 있는 color 변수는 type 추정 등이 전혀 안되어 사용 시 매우매우매우 불편함이 있음. (컬러 변수명이 생각 안날시 해당 파일을 직접 찾아가야 함)
<br>
<br>

원하는 솔루션 설명
---
컬러 변수를 타입 지원도 되고 편하게 쓸 수 있도록 수정.
<br>
<br>

해당 솔루션 구현에 대해 고려해본 사항이 있나요?
---
컬러 변수를 emotion theme으로 관리하면 좋을 것 같음.
<br>
<br>

추가 내용
---
하는김에 모듈로 만들어 사용하고 있는 media 객체도 theme으로 관리하는게 어떨지

**Comment by galaxy4276** [comment]
지속적인 개선사항은 100% 긍정 환영 입니다.
