### ISSUE TITLE
[BUG] 백엔드 개발자의 건강

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#318]
버그 설명
---
백엔드 개발자가 건강을 생각하지 않고 러쉬 중
<br>
<br>

재현하기 위해
---
버그가 발생하기 까지의 동작을 재현:
1. 오후 5시에 슬랙에 접속하여 백엔드 개발자가 개발 중인걸 확인
2. 새벽 3시에 슬랙에 접속하여 백엔드 개발자가 아직도 개발 중인걸 확인
<br>
<br>

예상했던 결과
---
건강을 생각하는 개발
<br>
<br>

스크린샷
---
![image](https://user-images.githubusercontent.com/57123802/133196378-03b885fa-cbac-446d-af59-96c3242eb64f.png)
<br>
<br>

추가 내용
---

**Comment by galaxy4276** [comment]
잠은 죽어서.

**Comment by bear-bear-bear** [comment]
건강 챙길때 close

**Comment by galaxy4276** [comment]
암 어 헬씨보이.
