### ISSUE TITLE
[FEATURE] 실제 서비스 환경에서 swr 로 요청을 보낼 시 헤더가 제대로 세팅되지 않는 문제

### ISSUE THREAD

**Issue by bear-bear-bear** [bear-bear-bear/mogakco#319]
버그 설명
---
swr로 로그인 시에 서버측에서 클라이언트측에 리프레쉬 토큰을 Cookie-set 해주는데, 로컬에선 제대로 쿠키에 저장되지만 실제 서비스 환경에선 쿠키에 토큰이 저장되지 않음. 서버측에선 성공적으로 200 응답을 내려줌.
<br>
<br>

재현하기 위해
---
버그가 발생하기 까지의 동작을 재현:
1. 실제 서비스 환경에서 로그인
2. 브라우저상에서 쿠키가 비어있는걸 확인
<br>
<br>

예상했던 결과
---
로컬과 같이 정상적으로 쿠키가 세팅됨
<br>
<br>

서버 로그 스크린샷
---
<br>
<br>

추가 내용
---
## 다음 해결 방법들 순차적으로 검토할 것
- [ ] [Off 'Secure' option if locally and doesn't have a cert](https://stackoverflow.com/questions/18795220/set-cookie-header-not-working/18795692#18795692) 
- [ ] [access-control-expose-headers](https://stackoverflow.com/questions/18795220/set-cookie-header-not-working/63055133#63055133)
- [ ] [How to send headers using swr](https://stackoverflow.com/questions/65862928/how-to-send-headers-using-swr)
- [ ] (이건 아닌 것 같지만 그냥 올림) [Delete cookie manually](https://goni9071.tistory.com/410)
- [ ] [다시 살펴보는 CORS](https://siosio3103.medium.com/cors-%EC%9D%B4%EC%A0%A0-%EB%81%9D%EB%82%B4%EB%B3%B4%EC%9E%90-e4cedce3d1c)

**Comment by galaxy4276** [comment]
서로 다른 도메인 간 인증 ( 쿠키 ) 를 공유하고 ( 서버 프런트 둘 다 credentials: true )
cors 또한 always allow 를 수행하고 있는 상황에서 발생 중이니 점검 중입니다.

**Comment by bear-bear-bear** [comment]
![image](https://user-images.githubusercontent.com/57123802/133260803-af4ec0e0-f3cd-44ae-b14c-91410ec1cc54.png)

**Comment by bear-bear-bear** [comment]
https 도입 후 close

**Comment by galaxy4276** [comment]
같은 리눅스 서버의 동시 운영으로 해결
