### ISSUE TITLE
[FEATURE] 채팅 부분 프런트엔드 작업 요청

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#324]
어떤 문제에 대한 기능 요청인지 설명
---
<br>
현재 백엔드 작업 부분이 많은 관계로 불가피하게 프런트까지 꼼꼼히 진행하기엔 일을 분담하는게 더 효율이 나을 거같아 작성합니다.

 채팅방 프런트엔드에 관해 필요기능에 대해 UI 를 보충해주시고,
제가 작성한 스타일을 보완해주세요.

또한 전반적인 프런트 로직 보완 및 개선 요청 드립니다.
<br>

원하는 솔루션 설명
---
<br>

- 필요 기능에 대해는 슬랙으로 이런 기능을 UI 로 넣어두겠다. 등 한 줄 의견 부탁드립니다.
-  추가 UI 기능 현재는 퇴장 제외하고는 크게 보이지 않는 듯 해요.
- 멤버 수 표현 스타일을 보완해주세요.
- 채팅 치는 부분에서 UI 보완해주세요. ( file 업로드 하는 부분이 너무 공간이 큰 거 같음 )
- 채팅을 쳤을 때, 맨 마지막 문자가 끊어서 서버로 발송되는 문제 해결해주세요.
![image](https://user-images.githubusercontent.com/50310464/133355582-ebf5b74a-584e-4964-aec5-3e2bde15a159.png)
( 프런트 chat 을 log 로 찍어보면 2번 간다. )
- alt + enter 로 들여쓰기 했을 때 서버로 \n 도 포함해서 전송되게 끔 수정해주세요. ( 들여쓰기 스타일  공백도 큰 듯합니다. )
![image](https://user-images.githubusercontent.com/50310464/133355669-d0b7ff67-04f8-4447-aa0e-f278fd7bb5cc.png)
( 공백 너무 큰 듯 함. 이러면 모든 문자가 합쳐져서 간다. )
<br>

해당 솔루션 구현에 대해 고려해본 사항이 있나요?
---
<br>
<br>

추가 내용
---

**Comment by galaxy4276** [comment]
전체적인 느낌은 스타일 보완이며,
기능적으로는 프런트엔드에서 채팅에 관해,
추가적인 UI 구현은 퇴장 버튼 디자인 및 배치입니다.

**Comment by galaxy4276** [comment]
현재 백엔드 부분 작업 처리 속도가 원활하지 못하고 있어서 ( 테스트 및 배포 서버 구성 포함 )
프런트엔드 작업 부탁드리겠습니다. @bear-bear-bear

**Comment by galaxy4276** [comment]
솔루션 설명에 작업 하나하나 마다 제가 슬랙 온라인이면 작업 전에 문의 한번 씩 주세요.
작업 전 서로 조금 소통하면 준재형이 더 빠르게 작업하실 수 있을 것 같아서요.

**Comment by bear-bear-bear** [comment]
확인했어요
