### ISSUE TITLE
[BUG] 마이페이지 toString 에러

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#341]
버그 설명
---
해당 데이터 원형에서 없는 함수 사용

재현하기 위해
---
버그가 발생하기 까지의 동작을 재현:
1. 마이페이지 계정 설정 접속

추가 내용
---
![image](https://user-images.githubusercontent.com/50310464/133763091-fa7b94d0-0eba-4252-b317-0f29d434d2fe.png)

**Comment by bear-bear-bear** [comment]
선택정보는 비어있을수도 있다는걸 망각했네요 확인 감사합니다. 새벽중 수정하겠습니다.

**Comment by bear-bear-bear** [comment]
위 코멘트는 코드 확인 안하고 답한건데, 코드 열어보니 null에 대한 처리는 제대로 되어있네요.

**Comment by bear-bear-bear** [comment]
![image](https://user-images.githubusercontent.com/57123802/133825259-31bebfcd-dfe9-49a9-8f05-3ccb88648fee.png)
백엔드 측에서 skills와 jobs에 대한 응답이 이전과 다르군요. 이전엔 generalResponse 형식으로 주지 않았는데 지금은 저렇게 주시네용. 혹시 말씀하셨었는데 제가 확인하지 못했었나염?

**Comment by bear-bear-bear** [comment]
일단 맞춰서 수정한 다음 PR 올릴게요 :)

**Comment by bear-bear-bear** [comment]
closed by #343

**Comment by bear-bear-bear** [comment]
.next 다시 빌드하셔야 변경사항 적용됩니다. @galaxy4276

**Comment by galaxy4276** [comment]
2개의 PR 에서 내용 변경에 따른 내용을 다뤘습니다.
Swagger 에서 또한 내용을 다루는데
다음부터 고지해드리겠습니다.
