### ISSUE TITLE
개발자 정신 차리기

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#373]
어떤 문제에 대한 기능 요청인지 설명
---
 백엔드 개발자가 정신을 못차림
 1. 컴퓨터 살짝만 건드려도 종료 중.
 > 발로 살짝 툭 치거나, 송이가 와서 선건들면 ( 내장이 다 튀어나와있음 ) 컴퓨터가 종료되고 있다. ( 커피쏟고 지지대 무너진 사건 유력 추정 )
 2. 1차 부작용 혹은 감염 ( 가족 전체가 1차에 대한 부작용을 한달 정도 겪는 것 같다. 무력하고 피곤함, 어머니 2차 접종 금지 설득 중 )
 3. 육아에 대한 강박 ( 부모님 홍송이 파양이야기 중.. 그 외 돌보기 전부 내 담당, 하루종일 울타리에 넣어놓기 너무 미안함  )
 
3일 동안 도커만지고 레디스 기능 개발한게 전부다.

원하는 솔루션 설명
---
(Ex - 페이지 맨 위로 한번에 이동시켜주는 기능 추가)
<br>
악으로 깡으로 버티기. 정신줄놓지말기
<br>

해당 솔루션 구현에 대해 고려해본 사항이 있나요?
---
(Ex - 페이지 맨 위로 한번에 이동시켜주는 버튼을 position: fixed로 페이지 우측 하단에 항상 띄워두면 좋을 것 같아요)
(Ex - 구현을 위해서 [Element.scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) 을 사용하면 될 것 같아요)
<br>
<br>

추가 내용
---
문제에 대한 추가 내용이 있다면 여기에 적어주세요.

**Comment by bear-bear-bear** [comment]
아 파양.. 어떡하냐 너 군대가면

**Comment by bear-bear-bear** [comment]
쉬면서 하셔도 됩니다 프런트 별도 작업 가능사항부터 작업할게요
