### ISSUE TITLE
프런트엔드 eslint 제안

### ISSUE THREAD

**Issue by galaxy4276** [bear-bear-bear/mogakco#91]
'no-shadow': 'off',
    'no-shadow-restricted-names': 'off',

프런트엔드 두 옵션이 off 인게 바람직한 지 잘 모르겠네요.
error 때문에 개발이 불편하시다면 warn 으로 설정해두시는게 어떨까요?
@bear-bear-bear @wscrg

**Comment by wscrg** [comment]
인정합니다

**Comment by galaxy4276** [comment]
대신 CI 에서는 따로 작성한 스크립트로 검사해서 에러 체킹하게 변경 할겁니다.

**Comment by bear-bear-bear** [comment]
타당하다고 봅니다

**Comment by bear-bear-bear** [comment]
[#102](https://github.com/bear-bear-bear/mogakco/pull/102)
